import { PrivateRoute } from '@/components/PrivateRoute';
import ToastCustom from '@/components/Toast';
import { AuthProvider } from '@/contexts/AuthContext';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body suppressHydrationWarning>
        <ToastCustom />
        <AuthProvider>
          <div className="bg-zinc-800 min-h-screen">
            <PrivateRoute>{children}</PrivateRoute>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
